version: '3'
services:
  mysql_8.0.27:
    #构建mysql镜像
    image: mysql:8.0.27
    container_name: mysql_8.0.27 # 容器名
    #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
    #      MYSQL_USER: test   #创建test用户
    #      MYSQL_PASSWORD: test  #设置test用户的密码
    ports:
      - '3306:3306'  #host物理直接映射端口为3306
    volumes:
      #mysql数据库挂载到host物理机目录
      - ./data/db:/var/lib/mysql
      #容器的配置目录挂载到host物理机目录
      - ./data/conf:/etc/mysql/conf.d