version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    privileged: true # 解决nginx文件的权限问题
    ports:
      - '80:80'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./html:/html
