
version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_USER=admin   # 指定用户名
      - NACOS_PASS=123456  # 指定密码
    volumes:
      - ./data:/home/nacos/data
      - ./logs:/home/nacos/logs
      - ./init.d:/home/nacos/init.d
