version: '3'
services:
  desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    environment:
      VNC_PW: "yourpassword"
      VNC_RESOLUTION: "1280x720"
      PULSE_SERVER: "tcp:desktop-pulseaudio:4713"
    volumes:
      - "./data:/data"
    ports:
      - "6080:80"
    depends_on:
      - pulseaudio
    networks:
      - vnc-network
  pulseaudio:
    image: jess/pulseaudio
    environment:
      PULSE_SERVER: "tcp:0.0.0.0:4713"
      PULSE_COOKIE: "/run/pulse/cookie"
      PULSE_COOKIE_MODE: "0600"
    volumes:
      - "./pulse:/run/pulse"
    networks:
      - vnc-network
networks:
  vnc-network:
