version: '3.5'

services:
  ubuntu-xfce-vnc:
    container_name: xfce
    image: dorowu/ubuntu-desktop-lxde-vnc:focal # 拉取Ubuntu 20.04 (latest)
    shm_size: "2gb"  # 指定内存大小
    ports:
      - 5900:5900
      - 6080:6080   # 访问端口
    environment:
      - VNC_PASSWD=123456    # 密码
      - GEOMETRY=1920x1080      # 屏幕分辨率
      - DEPTH=32               # 颜色位数，即画质
    volumes:
      - ./Downloads:/root/Downloads
      - ./Documents:/root/Documents
      - ./Pictures:/root/Pictures
      - ./Videos:/root/Videos
      - ./Music:/root/Music
    restart: unless-stopped
