version: '3'
services:
  ubuntu-desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "6080:80"
    environment:
      - VNC_COL_DEPTH=24
      - VNC_RESOLUTION=1280x800
      - AUDIO_DEVICE=hw:0,0
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./shared:/root/shared
